import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Header from "~/components/header/Header";
import Footer from "~/components/footer/Footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Insert name</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className="flex h-screen w-screen flex-col justify-center ">
        <div className="h-30% flex w-screen justify-between bg-accent-strong p-10">
          <h1 className="text-info">NetworkBrain</h1>
          <Image src="/brain.jpg" width={300} height={300} alt=""></Image>
        </div>
        <div className="h-30% w-screen bg-black"></div>
      </div>
      <Footer></Footer>
    </>
  );
};

export default Home;
